module.exports = Object.freeze({
    SIGNUP_SUCCESS_MSG: 'Successfully Signup',
    ERR_MSG: 'Internal server error',
    GET_FILE_MSG: 'Found files',
    LOGIN_EMAIL_NOT_FOUND: 'Email is exist',
    FILE_NOT_FOUND: 'File not found',
    ROUND: 10,
    FOUND_USER_LIST: 'User details fetched successfully!',
    PASSWORD_DOES_NOT_MATCH: 'Password does not match',
    COULD_NOT_LOGIN: 'Could not login',
    LOGIN_SUCCESS_MSG: 'Logged in successfully',
    EMAIL_NOT_FOUND: "Email does not exist",
    FILE_DOES_NOT_EXIST: 'File does not exist',
    ERROR_MSG: 'Email is not match',
    PERMISSION_CHNG_SUCCESS: 'Permission changed successfully!',
    PASSWORD_NOT_MATCH: 'Wrong password',
    FILE_NOT_FOUND: 'File does not exists.',
    DONT_ACCESS_FOR_FILE: 'You do not have the access for this file.',
    FILE_UPLOAD_SUCCESS_MSG: 'Successfully uploaded file',
    NOT_FOUND_RECORD: 'No records found.',
    LOGIN_PASS_DONT_MATCH: 'Password do not match',
    UPLOAD_FILE_RECORD_FOUND: 'File record found.',
    INVALID_TOKEN: 'Invalid token',
    RECORD_TRUNCATED: 'Record has been truncated'
})